export const FETCH_MOVIE_COMPLETED = 'FETCH_MOVIE_COMPLETED';
export const FETCH_MOVIE_FAILED = 'FETCH_MOVIE_FAILED';
export const FETCH_MOVIES_COMPLETED = 'FETCH_MOVIES_COMPLETED';
export const FETCH_MOVIES_FAILED = 'FETCH_MOVIES_FAILED';
